apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  generateName: system:openshift:openshift-authenticator-
  labels:
    authentication.openshift.io/csr: openshift-authenticator
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQkRUQ0J0QUlCQURCU01WQXdUZ1lEVlFRREUwZHplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YjNCbApibk5vYVdaMExXOWhkWFJvTFdGd2FYTmxjblpsY2pwdmNHVnVjMmhwWm5RdFlYVjBhR1Z1ZEdsallYUnZjakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkw2VkhyZENabnBmaEp2Wnl0R09lWlhRVEhsQ3RSVE0KT1ZPRGY3aGI1SnJabjRNYzZuQzFRdkExM3NjaWxIVUZ3ei9oNXdsV25kalBTSE5qeFZ1K05HR2dBREFLQmdncQpoa2pPUFFRREFnTklBREJGQWlBWmljc3FzNHZITjFCV0ViZGxkZzNSYStGZmtrelRUZ3h0eEpjZDFqNVprZ0loCkFMSit3YjhxRytJWjdoZ2ZiY24wYzFiV2xYSDM3SE1PbXArcFpDUHN4bjhWCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
status: {}
