apiVersion: v1
data:
  v4-0-config-system-session: eyJraW5kIjoiU2Vzc2lvblNlY3JldHMiLCJhcGlWZXJzaW9uIjoib3BlcmF0b3J2MWNsaWVudCIsInNlY3JldHMiOlt7ImF1dGhlbnRpY2F0aW9uIjoiVnAza2t0NmF6MV9kWkFyR3RVRnNqTUY3bUwwYVBUdnNmUzlaU3JRem9pNE1EQmhuczd2MXgxcTFYLXJpa0c3byIsImVuY3J5cHRpb24iOiItc05LemJwUGc4Rkx4VFlVX2pNbERXYTRIVGpCbzhxbCJ9XX0=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: oauth-openshift
  name: v4-0-config-system-session
  namespace: openshift-authentication
